apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o9u3ancfs-python
  janus-idp.io/tekton: o9u3ancfs-python
  backstage.io/kubernetes-id: o9u3ancfs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o9u3ancfs-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
